

package GPS_MAP;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class MapSettings extends javax.swing.JFrame {
    
    public String ipAddress;
    public int portArduino;
    
    double lattitudeInSeconds;
    double longitudeInSeconds;

    double radius;

    public MapSettings() {
        
        initComponents();
        ImageIcon img = new ImageIcon(this.getClass().getResource("logo.png"));                    
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        distanceX = new javax.swing.JTextField();
        degreeLattitude = new javax.swing.JTextField();
        degreeLongitude = new javax.swing.JTextField();
        minuteLattitude = new javax.swing.JTextField();
        secondLattitude = new javax.swing.JTextField();
        minuteLongitude = new javax.swing.JTextField();
        secondLongitude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ip = new javax.swing.JTextField();
        port = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mongol Barota GPS Plotter");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Radius from control station:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Lattitude of control station:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Longitude of control station:");

        distanceX.setText("1000.00");
        distanceX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceXActionPerformed(evt);
            }
        });

        degreeLattitude.setText("23");
        degreeLattitude.setPreferredSize(new java.awt.Dimension(59, 25));

        degreeLongitude.setText("90");
        degreeLongitude.setPreferredSize(new java.awt.Dimension(59, 25));

        minuteLattitude.setText("48");
        minuteLattitude.setPreferredSize(new java.awt.Dimension(59, 25));

        secondLattitude.setText("41");
        secondLattitude.setPreferredSize(new java.awt.Dimension(59, 25));
        secondLattitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondLattitudeActionPerformed(evt);
            }
        });

        minuteLongitude.setText("24");
        minuteLongitude.setPreferredSize(new java.awt.Dimension(59, 25));

        secondLongitude.setText("18");
        secondLongitude.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel5.setText("Degree:");

        jLabel6.setText("Minute:");

        jLabel7.setText("Second:");

        jLabel8.setText("Degree:");

        jLabel9.setText("Minute:");

        jLabel10.setText("Second:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Meter");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GPS_MAP/logo.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("GPS Plotter Software");

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Mongol Barota");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Server IP Address:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Server Port:");

        ip.setText("192.168.1.7");

        port.setText("8888");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degreeLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeLattitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuteLattitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuteLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(secondLattitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(secondLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(port, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ip, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(distanceX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))))
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jLabel15)
                    .addContainerGap(110, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(port)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(distanceX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(degreeLattitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteLattitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondLattitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(degreeLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double lat_degree = 0; 
        double lat_minute = 0;
        double lat_second = 0;
        double lon_degree = 0; 
        double lon_minute = 0; 
        double lon_second = 0;
        
        ipAddress = ip.getText();
        String portString = port.getText();
        
        String distanceX_str = distanceX.getText();
                
        String lattitudeDegree = degreeLattitude.getText();
        String lattitudeMinute = minuteLattitude.getText();
        String lattitudeSecond = secondLattitude.getText();
        
        String longitudeDegree = degreeLongitude.getText();
        String longitudeMinute = minuteLongitude.getText();
        String longitudeSecond = secondLongitude.getText();
        
        boolean exceptionHappened = false;
        
        try
        {
            portArduino = Integer.parseInt(portString);
            radius = Double.parseDouble(distanceX_str);

            lat_degree = Double.parseDouble(lattitudeDegree);
            lat_minute = Double.parseDouble(lattitudeMinute);
            lat_second = Double.parseDouble(lattitudeSecond);

            lon_degree = Double.parseDouble(longitudeDegree);
            lon_minute = Double.parseDouble(longitudeMinute);
            lon_second = Double.parseDouble(longitudeSecond);
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "Please fill up every field.", "Empty String Found", JOptionPane.WARNING_MESSAGE);
            exceptionHappened = true;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Invalid Input.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            exceptionHappened = true;
        }
        
        if(exceptionHappened == false)
        {
            if(radius<=100 || radius> 5000 || ipAddress.equals("") || portString.equals(""))
            {
                if(ipAddress.equals(""))
                    JOptionPane.showMessageDialog(null, "You must input an ip address", "Invalid Input.", JOptionPane.WARNING_MESSAGE);
                else if(portString.equals(""))
                    JOptionPane.showMessageDialog(null, "You must input a port number.", "Invalid Input.", JOptionPane.WARNING_MESSAGE);
                else if(radius>500)
                    JOptionPane.showMessageDialog(null, "Radius is out of range.", "Invalid Input.", JOptionPane.WARNING_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "Radius is too small", "Invalid Input.", JOptionPane.WARNING_MESSAGE);

            }
            else
            {
                if(radius<0 || lat_degree <0 || lat_degree >= 360 || lat_minute < 0 || lat_minute >= 60 || lat_second < 0 || lat_second >= 60
                    || lon_degree < 0 || lon_degree >= 360 || lon_minute < 0 || lon_minute >= 60 || lon_second < 0 || lon_second >= 60)
                {
                    JOptionPane.showMessageDialog(null, "Invalid GPS data.", "Invalid Input.", JOptionPane.WARNING_MESSAGE);

                }
                else
                {

                    lattitudeInSeconds = (lat_degree * 3600) + (lat_minute * 60) + lat_second;
                    longitudeInSeconds = (lon_degree * 3600) + (lon_minute * 60) + lon_second;


                    GPS_MAP.F = new JFrame();
                    GPS_MAP.F.setTitle("Mongol Barota GPS Plotter");
                    GPS_MAP.F.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    GPS_MAP.F.setSize(1350, 750);
                    GPS_MAP.F.setLocationRelativeTo(null);
                    GPS_MAP.F.setResizable(false);

                    try 
                    {
                        GPS_MAP.M = new Map();
                    } 
                    catch (UnknownHostException ex) 
                    {
                        Logger.getLogger(MapSettings.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    catch (IOException ex) {
                        Logger.getLogger(MapSettings.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    

                    GPS_MAP.MasterPanel = new JPanel();
                    GPS_MAP.MasterPanel.setBackground(Color.LIGHT_GRAY);
                    GPS_MAP.InputPanel = new otherPanel();

                    GPS_MAP.MasterPanel.add(GPS_MAP.M);

                    GPS_MAP.MasterPanel.add(GPS_MAP.InputPanel);
                    GPS_MAP.F.add(GPS_MAP.MasterPanel);
                    
                    ImageIcon img=new ImageIcon(this.getClass().getResource("logo.png"));                    
                    GPS_MAP.F.setIconImage(img.getImage());
        
                    GPS_MAP.F.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) 
                    {
                            try 
                            {
                                
                                GPS_MAP.M.UDP.endConnection();
                            
                            } catch (UnknownHostException ex) {
                                Logger.getLogger(MapSettings.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (IOException ex) {
                                Logger.getLogger(MapSettings.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    }
                    });
                    

                    GPS_MAP.F.setVisible(true);

                    this.setVisible(false);
                }
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void secondLattitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondLattitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondLattitudeActionPerformed

    private void distanceXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanceXActionPerformed
    public double getLattitudeInSeconds()
    {
        return lattitudeInSeconds;
        
    }
    public double getRadius()
    {
        return radius;
        
    }

    
    public double getLongitudeInSeconds()
    {
        return longitudeInSeconds;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MapSettings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField degreeLattitude;
    private javax.swing.JTextField degreeLongitude;
    private javax.swing.JTextField distanceX;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField minuteLattitude;
    private javax.swing.JTextField minuteLongitude;
    private javax.swing.JTextField port;
    private javax.swing.JTextField secondLattitude;
    private javax.swing.JTextField secondLongitude;
    // End of variables declaration//GEN-END:variables
}
